### ISSUE TITLE
<title> not rendered if using react-helmet v5

### ISSUE THREAD

**Issue by Jinksi** [superhighfives/an-almost-static-stack#1]
Just a heads up for anyone else who has the same issue.
react-snapshot doesn't seem to crawl the `<title>` injected by react-helmet@5.0.2.
I also tried with react-helmet 5.0.0 & 5.0.1.
I couldn't figure it out, so I just rolled back to react-helmet@4.0.0 😅.

**Comment by superhighfives** [comment]
Thanks for sharing, @Jinksi. I'll close this for now, but it'd certainly be worth opening an issue on react-helmet and referring to this.
