### ISSUE TITLE
How to deal with async data rendering?

### ISSUE THREAD

**Issue by johnlin0207** [superhighfives/an-almost-static-stack#13]
I set a timer to rendering data,but it can't fetch the async data,so how to deal with async data rendering?Like ajax data

**Comment by johnlin0207** [comment]
react-snapshot -> snapshotDelay
but also didn't make it work

**Comment by superhighfives** [comment]
Hey @johnlin0207! I believe react-snapshot is no longer maintained, so I'd recommend checking out https://github.com/stereobooster/react-snap.
